### ISSUE TITLE
Change date formatting from "8 years ago" to "8y" to prevent long strings?

### ISSUE THREAD

**Issue by yewsiang** [frizensami/webpage-discussion-extension#14]
![Screenshot 2022-02-22 at 12 15 09 AM](https://user-images.githubusercontent.com/14248879/154992291-68afd1f4-bf0d-4957-9ed8-24dc13c342dd.png)

**Comment by frizensami** [comment]
Have to replace `fromnow` library

**Comment by frizensami** [comment]
Okay, so hacker news uses `fromnow` to convert date to string, but reddit API already returns in e.g., `2 months ago` format.
Bit of a pain to standardize, easiest but most inefficient way would be to do a mass regex replace of years/months/... with y/mo/...
