### ISSUE TITLE
Should we make the extension slightly transparent?

### ISSUE THREAD

**Issue by frizensami** [frizensami/webpage-discussion-extension#2]
Since extension covers part of the site, having it be slightly transparent will make sure users don't miss important buttons etc.

**Comment by yewsiang** [comment]
I think being slightly transparent can make reading the sidebar to be quite challenging? I'm hoping that the keyboard shortcuts would be enough, since it would allow users to easily toggle between open/closed

**Comment by frizensami** [comment]
Okay I added a opacity: 0.95 just for testing, lmk what you think. I think it keeps readability but still shows that there's something in the background behind it 

![image](https://user-images.githubusercontent.com/5507069/154827958-6e34f8cc-581b-4e1a-96b6-414bf07c119a.png)

Also maybe opacity is something the user will want to set in the future?

**Comment by yewsiang** [comment]
My personal preference is to be fully opaque, but we'll be adding in the settings icon to allow users to customise the UI so this can be one of the customizations
